name: Build & Push AI Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./ai-reco
          file: ./ai-reco/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trackfit-ai:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/trackfit-ai:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/trackfit-ai:cache,mode=max
